# GENERATED by tools/gen-protos.sh (run via `tox -egenprotos`).
# Do not edit this file by hand -- your changes will be overwritten the next
# time the protos are regenerated.
#
# CONTRACT_HASH is the sha256 of kerbside.proto's raw bytes. It is compared
# against the Rust kerbside-proxy binary's compile-time-embedded hash by
# kerbside/proxy_supervisor.py before launching the proxy, so a Python/Rust
# pairing that disagrees on the RPC contract is refused at startup instead
# of failing subtly at connection time.
CONTRACT_HASH = 'f06c4ef819009d68c0d0e91ff3ea3fa1b53f3d4cfe6a16efa4510f951e988291'
