"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StatusReply(_message.Message):
    """StatusReply is the generic reply for the bookkeeping RPCs. success/error
    carry the application-level outcome of the write. Transport and internal
    errors are signalled via gRPC status codes, not these fields.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StatusReply: _TypeAlias = StatusReply  # noqa: Y015

@_typing.final
class AuthorizeConnectionRequest(_message.Message):
    """AuthorizeConnectionRequest carries everything the proxy has recovered by
    the time it needs an authorization decision.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    CONNECTION_REF_FIELD_NUMBER: _builtins.int
    CLIENT_IP_FIELD_NUMBER: _builtins.int
    CLIENT_PORT_FIELD_NUMBER: _builtins.int
    CONNECTION_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_TYPE_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    token: _builtins.str
    """token is the RSA-decrypted plaintext the proxy recovered from the SPICE
    client's encrypted password (phase 1, decrypt_password).
    """
    connection_ref: _builtins.str
    """connection_ref is a proxy-generated per-connection identifier that
    replaces the per-worker pid identity in proxychannels.
    """
    client_ip: _builtins.str
    client_port: _builtins.int
    connection_id: _builtins.int
    channel_type: _builtins.str
    channel_id: _builtins.int
    def __init__(
        self,
        *,
        token: _builtins.str = ...,
        connection_ref: _builtins.str = ...,
        client_ip: _builtins.str = ...,
        client_port: _builtins.int = ...,
        connection_id: _builtins.int = ...,
        channel_type: _builtins.str = ...,
        channel_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "channel_type", b"channel_type", "client_ip", b"client_ip", "client_port", b"client_port", "connection_id", b"connection_id", "connection_ref", b"connection_ref", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuthorizeConnectionRequest: _TypeAlias = AuthorizeConnectionRequest  # noqa: Y015

@_typing.final
class Target(_message.Message):
    """Target is the successful authorization result: everything the proxy needs
    to open the upstream connection to the hypervisor. The first eight fields
    (hypervisor .. uuid) are exactly what the proxy reads from get_console;
    ca_cert comes from get_source; session_id comes from the resolved token.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HYPERVISOR_FIELD_NUMBER: _builtins.int
    HYPERVISOR_IP_FIELD_NUMBER: _builtins.int
    INSECURE_PORT_FIELD_NUMBER: _builtins.int
    SECURE_PORT_FIELD_NUMBER: _builtins.int
    TICKET_FIELD_NUMBER: _builtins.int
    CA_CERT_FIELD_NUMBER: _builtins.int
    HOST_SUBJECT_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    UUID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    hypervisor: _builtins.str
    hypervisor_ip: _builtins.str
    insecure_port: _builtins.int
    secure_port: _builtins.int
    ticket: _builtins.str
    ca_cert: _builtins.str
    host_subject: _builtins.str
    source: _builtins.str
    uuid: _builtins.str
    session_id: _builtins.str
    def __init__(
        self,
        *,
        hypervisor: _builtins.str = ...,
        hypervisor_ip: _builtins.str = ...,
        insecure_port: _builtins.int = ...,
        secure_port: _builtins.int = ...,
        ticket: _builtins.str = ...,
        ca_cert: _builtins.str = ...,
        host_subject: _builtins.str = ...,
        source: _builtins.str = ...,
        uuid: _builtins.str = ...,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ca_cert", b"ca_cert", "host_subject", b"host_subject", "hypervisor", b"hypervisor", "hypervisor_ip", b"hypervisor_ip", "insecure_port", b"insecure_port", "secure_port", b"secure_port", "session_id", b"session_id", "source", b"source", "ticket", b"ticket", "uuid", b"uuid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Target: _TypeAlias = Target  # noqa: Y015

@_typing.final
class Denied(_message.Message):
    """Denied is the unsuccessful authorization result, carrying a human-readable
    reason (unknown/expired token, unknown console, etc.).
    """

    DESCRIPTOR: _descriptor.Descriptor

    REASON_FIELD_NUMBER: _builtins.int
    reason: _builtins.str
    def __init__(
        self,
        *,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Denied: _TypeAlias = Denied  # noqa: Y015

@_typing.final
class FirewallPolicy(_message.Message):
    """FirewallPolicy carries the deployment-tunable firewall knobs the proxy
    enforces for one connection. Python owns policy and fills this from
    deployment-wide config; the Rust proxy builds the connection's enforcing
    policy from it ("Python decides policy; Rust enforces it"). For v1 the value
    is identical on every reply (deployment-wide), but the mechanism is
    per-connection so per-source/per-console policy is a later Python-only
    change.

    This carries ONLY the tunable knobs with a config surface today: the
    enforcement mode and the permitted channel set. The L1 message-type
    allowlist tables are a compiled-in fact about the SPICE protocol (not
    policy) and are NOT delivered here. Size caps, rate ceilings and per-verdict
    severities keep their enforcing compiled defaults in the proxy for v1 and are
    a future extension of this message (fields 3+ are reserved for them).
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Mode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FirewallPolicy._Mode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ENFORCE: FirewallPolicy._Mode.ValueType  # 0
        """Blocking verdicts are applied (recorded action=enforced)."""
        WARN_ONLY: FirewallPolicy._Mode.ValueType  # 1
        """Blocking verdicts are downgraded to forward + warn"""

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper):
        """How the proxy acts on a rule that decides to block a message. ENFORCE is
        the proto3 default (0), so an unset mode means enforce.
        """

    ENFORCE: FirewallPolicy.Mode.ValueType  # 0
    """Blocking verdicts are applied (recorded action=enforced)."""
    WARN_ONLY: FirewallPolicy.Mode.ValueType  # 1
    """Blocking verdicts are downgraded to forward + warn"""

    MODE_FIELD_NUMBER: _builtins.int
    PERMITTED_CHANNELS_FIELD_NUMBER: _builtins.int
    mode: Global___FirewallPolicy.Mode.ValueType
    @_builtins.property
    def permitted_channels(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The ChannelType discriminants (values 1..=11: main=1, display=2, inputs=3,
        cursor=4, playback=5, record=6, tunnel=7, smartcard=8, usbredir=9,
        port=10, webdav=11) the deployment permits the proxy to relay. A channel
        not in this set is denied before relay (PermissionDenied), same shape as
        the existing unknown-channel rejection.

        An EMPTY list means "permit all": a deployment that restricts channels
        lists the permitted ones, while permitting NONE is nonsensical (it would
        block every connection). Documented identically on the Rust side.
        """

    def __init__(
        self,
        *,
        mode: Global___FirewallPolicy.Mode.ValueType = ...,
        permitted_channels: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mode", b"mode", "permitted_channels", b"permitted_channels"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FirewallPolicy: _TypeAlias = FirewallPolicy  # noqa: Y015

@_typing.final
class AuthorizeConnectionReply(_message.Message):
    """AuthorizeConnectionReply is either a Denied or a Target. The oneof makes
    the deny/allow decision explicit and unambiguous at the wire level.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DENIED_FIELD_NUMBER: _builtins.int
    TARGET_FIELD_NUMBER: _builtins.int
    FIREWALL_POLICY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def denied(self) -> Global___Denied: ...
    @_builtins.property
    def target(self) -> Global___Target: ...
    @_builtins.property
    def firewall_policy(self) -> Global___FirewallPolicy:
        """The firewall policy the proxy must enforce for this connection. Present
        ONLY on the success (target) path; a Denied reply carries no policy. Being
        a message field it is presence-tracked (Option in prost, HasField in
        Python), so an older daemon that never sets it is handled by the proxy
        falling back to its enforcing compiled default.
        """

    def __init__(
        self,
        *,
        denied: Global___Denied | None = ...,
        target: Global___Target | None = ...,
        firewall_policy: Global___FirewallPolicy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["denied", b"denied", "firewall_policy", b"firewall_policy", "result", b"result", "target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["denied", b"denied", "firewall_policy", b"firewall_policy", "result", b"result", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["denied", "target"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___AuthorizeConnectionReply: _TypeAlias = AuthorizeConnectionReply  # noqa: Y015

@_typing.final
class RegisterChannelRequest(_message.Message):
    """RegisterChannelRequest records the pre-authorization channel identity
    (maps to record_channel_info_by_ref).
    """

    DESCRIPTOR: _descriptor.Descriptor

    NODE_FIELD_NUMBER: _builtins.int
    CONNECTION_REF_FIELD_NUMBER: _builtins.int
    CLIENT_IP_FIELD_NUMBER: _builtins.int
    CLIENT_PORT_FIELD_NUMBER: _builtins.int
    CONNECTION_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_TYPE_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    node: _builtins.str
    connection_ref: _builtins.str
    client_ip: _builtins.str
    client_port: _builtins.int
    connection_id: _builtins.int
    channel_type: _builtins.str
    channel_id: _builtins.int
    def __init__(
        self,
        *,
        node: _builtins.str = ...,
        connection_ref: _builtins.str = ...,
        client_ip: _builtins.str = ...,
        client_port: _builtins.int = ...,
        connection_id: _builtins.int = ...,
        channel_type: _builtins.str = ...,
        channel_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "channel_type", b"channel_type", "client_ip", b"client_ip", "client_port", b"client_port", "connection_id", b"connection_id", "connection_ref", b"connection_ref", "node", b"node"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterChannelRequest: _TypeAlias = RegisterChannelRequest  # noqa: Y015

@_typing.final
class AuditEventRequest(_message.Message):
    """AuditEventRequest maps to add_audit_event()."""

    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FIELD_NUMBER: _builtins.int
    UUID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_FIELD_NUMBER: _builtins.int
    NODE_FIELD_NUMBER: _builtins.int
    CONNECTION_REF_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    uuid: _builtins.str
    session_id: _builtins.str
    channel: _builtins.str
    node: _builtins.str
    connection_ref: _builtins.str
    message: _builtins.str
    def __init__(
        self,
        *,
        source: _builtins.str = ...,
        uuid: _builtins.str = ...,
        session_id: _builtins.str = ...,
        channel: _builtins.str = ...,
        node: _builtins.str = ...,
        connection_ref: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel", b"channel", "connection_ref", b"connection_ref", "message", b"message", "node", b"node", "session_id", b"session_id", "source", b"source", "uuid", b"uuid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuditEventRequest: _TypeAlias = AuditEventRequest  # noqa: Y015

@_typing.final
class DeregisterChannelRequest(_message.Message):
    """DeregisterChannelRequest maps to remove_proxy_channel(node, connection_ref)."""

    DESCRIPTOR: _descriptor.Descriptor

    NODE_FIELD_NUMBER: _builtins.int
    CONNECTION_REF_FIELD_NUMBER: _builtins.int
    node: _builtins.str
    connection_ref: _builtins.str
    def __init__(
        self,
        *,
        node: _builtins.str = ...,
        connection_ref: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["connection_ref", b"connection_ref", "node", b"node"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeregisterChannelRequest: _TypeAlias = DeregisterChannelRequest  # noqa: Y015

@_typing.final
class ClearNodeChannelsRequest(_message.Message):
    """ClearNodeChannelsRequest maps to remove_node_channels(node)."""

    DESCRIPTOR: _descriptor.Descriptor

    NODE_FIELD_NUMBER: _builtins.int
    node: _builtins.str
    def __init__(
        self,
        *,
        node: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["node", b"node"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClearNodeChannelsRequest: _TypeAlias = ClearNodeChannelsRequest  # noqa: Y015

@_typing.final
class ProxyControlRequest(_message.Message):
    """ProxyControlRequest opens the control stream for a given proxy node."""

    DESCRIPTOR: _descriptor.Descriptor

    NODE_FIELD_NUMBER: _builtins.int
    node: _builtins.str
    def __init__(
        self,
        *,
        node: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["node", b"node"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProxyControlRequest: _TypeAlias = ProxyControlRequest  # noqa: Y015

@_typing.final
class ProxyControlEvent(_message.Message):
    """ProxyControlEvent is a single event pushed to the proxy over the control
    stream. The oneof is intentionally extensible (e.g. future policy-push).
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEARTBEAT_FIELD_NUMBER: _builtins.int
    TERMINATE_SESSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def heartbeat(self) -> Global___Heartbeat: ...
    @_builtins.property
    def terminate_session(self) -> Global___TerminateSession: ...
    def __init__(
        self,
        *,
        heartbeat: Global___Heartbeat | None = ...,
        terminate_session: Global___TerminateSession | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "heartbeat", b"heartbeat", "terminate_session", b"terminate_session"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "heartbeat", b"heartbeat", "terminate_session", b"terminate_session"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["heartbeat", "terminate_session"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___ProxyControlEvent: _TypeAlias = ProxyControlEvent  # noqa: Y015

@_typing.final
class Heartbeat(_message.Message):
    """Heartbeat is an empty keepalive event."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Heartbeat: _TypeAlias = Heartbeat  # noqa: Y015

@_typing.final
class TerminateSession(_message.Message):
    """TerminateSession instructs the proxy to tear down a session."""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TerminateSession: _TypeAlias = TerminateSession  # noqa: Y015
