"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from kerbside.rpc import kerbside_pb2 as _kerbside_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class KerbsideProxyStub:
    """KerbsideProxy is the control-plane RPC contract between the Rust SPICE
    proxy and the Kerbside daemon. Rather than the proxy touching MariaDB
    directly, Python owns policy and the database and the proxy consults this
    service.

    The service is hosted over a filesystem-guarded unix domain socket using
    insecure gRPC credentials (the peer is a trusted local process). Errors
    are signalled via gRPC status codes (context.set_code/set_details), NOT
    via fields on the reply messages. The StatusReply.success/error fields
    exist only to carry an application-level "did the bookkeeping write
    happen" result for the fire-and-forget bookkeeping RPCs; transport and
    internal failures use gRPC status codes.

    Each RPC maps to one or more of the db.py operations the proxy performs
    today (see per-RPC comments below).
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> KerbsideProxyAsyncStub: ...
    AuthorizeConnection: _grpc.UnaryUnaryMultiCallable[_kerbside_pb2.AuthorizeConnectionRequest, _kerbside_pb2.AuthorizeConnectionReply]
    """AuthorizeConnection is the core authorization call. It collapses the
    proxy's four current db.py operations into a single round trip at the
    connection decision point:
      get_token_by_token(token)   -- resolves the decrypted token plaintext,
                                     preserving the server-side expires>now
                                     filter (expired tokens are denied).
      get_source(source)          -- reads the source's ca_cert.
      get_console(source, uuid)   -- reads the hypervisor target details.
      record_channel_info_by_ref(session_id)  -- records the resolved
                                     session_id against the channel on success.
      add_audit_event('Channel created')  -- writes the creation audit event
                                     on success.
    On success it returns a Target; on any miss it returns a Denied.
    """
    RegisterChannel: _grpc.UnaryUnaryMultiCallable[_kerbside_pb2.RegisterChannelRequest, _kerbside_pb2.StatusReply]
    """RegisterChannel records the pre-authorization channel identity. It maps
    to record_channel_info_by_ref (the (node, connection_ref) upsert with the
    client/connection/channel identity fields), before the token has been
    authorized.
    """
    RecordAuditEvent: _grpc.UnaryUnaryMultiCallable[_kerbside_pb2.AuditEventRequest, _kerbside_pb2.StatusReply]
    """RecordAuditEvent writes an audit event. It maps to add_audit_event() and
    carries the hypervisor connect success/failure and stall events the
    proxy emits during a connection's lifetime.
    """
    DeregisterChannel: _grpc.UnaryUnaryMultiCallable[_kerbside_pb2.DeregisterChannelRequest, _kerbside_pb2.StatusReply]
    """DeregisterChannel removes a channel record at teardown. It maps to
    remove_channel_by_ref(), keyed on connection_ref alone (which is
    unique). The request carries node for symmetry with the other RPCs and
    possible future scoping, but the handler does not currently read it.
    """
    ClearNodeChannels: _grpc.UnaryUnaryMultiCallable[_kerbside_pb2.ClearNodeChannelsRequest, _kerbside_pb2.StatusReply]
    """ClearNodeChannels clears all stale channel records for a node at proxy
    startup. It maps to remove_node_channels(node).
    """
    ProxyControl: _grpc.UnaryStreamMultiCallable[_kerbside_pb2.ProxyControlRequest, _kerbside_pb2.ProxyControlEvent]
    """ProxyControl is a server-streaming control channel from the daemon to
    the proxy. It delivers TerminateSession events (interleaved with
    Heartbeat keepalives) for sessions marked for termination that are live
    on this node. The ProxyControlEvent oneof is intentionally extensible
    (e.g. for future policy-push events); keep it extensible.
    """

@_typing.type_check_only
class KerbsideProxyAsyncStub(KerbsideProxyStub):
    """KerbsideProxy is the control-plane RPC contract between the Rust SPICE
    proxy and the Kerbside daemon. Rather than the proxy touching MariaDB
    directly, Python owns policy and the database and the proxy consults this
    service.

    The service is hosted over a filesystem-guarded unix domain socket using
    insecure gRPC credentials (the peer is a trusted local process). Errors
    are signalled via gRPC status codes (context.set_code/set_details), NOT
    via fields on the reply messages. The StatusReply.success/error fields
    exist only to carry an application-level "did the bookkeeping write
    happen" result for the fire-and-forget bookkeeping RPCs; transport and
    internal failures use gRPC status codes.

    Each RPC maps to one or more of the db.py operations the proxy performs
    today (see per-RPC comments below).
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    AuthorizeConnection: _aio.UnaryUnaryMultiCallable[_kerbside_pb2.AuthorizeConnectionRequest, _kerbside_pb2.AuthorizeConnectionReply]  # type: ignore[assignment]
    """AuthorizeConnection is the core authorization call. It collapses the
    proxy's four current db.py operations into a single round trip at the
    connection decision point:
      get_token_by_token(token)   -- resolves the decrypted token plaintext,
                                     preserving the server-side expires>now
                                     filter (expired tokens are denied).
      get_source(source)          -- reads the source's ca_cert.
      get_console(source, uuid)   -- reads the hypervisor target details.
      record_channel_info_by_ref(session_id)  -- records the resolved
                                     session_id against the channel on success.
      add_audit_event('Channel created')  -- writes the creation audit event
                                     on success.
    On success it returns a Target; on any miss it returns a Denied.
    """
    RegisterChannel: _aio.UnaryUnaryMultiCallable[_kerbside_pb2.RegisterChannelRequest, _kerbside_pb2.StatusReply]  # type: ignore[assignment]
    """RegisterChannel records the pre-authorization channel identity. It maps
    to record_channel_info_by_ref (the (node, connection_ref) upsert with the
    client/connection/channel identity fields), before the token has been
    authorized.
    """
    RecordAuditEvent: _aio.UnaryUnaryMultiCallable[_kerbside_pb2.AuditEventRequest, _kerbside_pb2.StatusReply]  # type: ignore[assignment]
    """RecordAuditEvent writes an audit event. It maps to add_audit_event() and
    carries the hypervisor connect success/failure and stall events the
    proxy emits during a connection's lifetime.
    """
    DeregisterChannel: _aio.UnaryUnaryMultiCallable[_kerbside_pb2.DeregisterChannelRequest, _kerbside_pb2.StatusReply]  # type: ignore[assignment]
    """DeregisterChannel removes a channel record at teardown. It maps to
    remove_channel_by_ref(), keyed on connection_ref alone (which is
    unique). The request carries node for symmetry with the other RPCs and
    possible future scoping, but the handler does not currently read it.
    """
    ClearNodeChannels: _aio.UnaryUnaryMultiCallable[_kerbside_pb2.ClearNodeChannelsRequest, _kerbside_pb2.StatusReply]  # type: ignore[assignment]
    """ClearNodeChannels clears all stale channel records for a node at proxy
    startup. It maps to remove_node_channels(node).
    """
    ProxyControl: _aio.UnaryStreamMultiCallable[_kerbside_pb2.ProxyControlRequest, _kerbside_pb2.ProxyControlEvent]  # type: ignore[assignment]
    """ProxyControl is a server-streaming control channel from the daemon to
    the proxy. It delivers TerminateSession events (interleaved with
    Heartbeat keepalives) for sessions marked for termination that are live
    on this node. The ProxyControlEvent oneof is intentionally extensible
    (e.g. for future policy-push events); keep it extensible.
    """

class KerbsideProxyServicer(metaclass=_abc_1.ABCMeta):
    """KerbsideProxy is the control-plane RPC contract between the Rust SPICE
    proxy and the Kerbside daemon. Rather than the proxy touching MariaDB
    directly, Python owns policy and the database and the proxy consults this
    service.

    The service is hosted over a filesystem-guarded unix domain socket using
    insecure gRPC credentials (the peer is a trusted local process). Errors
    are signalled via gRPC status codes (context.set_code/set_details), NOT
    via fields on the reply messages. The StatusReply.success/error fields
    exist only to carry an application-level "did the bookkeeping write
    happen" result for the fire-and-forget bookkeeping RPCs; transport and
    internal failures use gRPC status codes.

    Each RPC maps to one or more of the db.py operations the proxy performs
    today (see per-RPC comments below).
    """

    @_abc_1.abstractmethod
    def AuthorizeConnection(
        self,
        request: _kerbside_pb2.AuthorizeConnectionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kerbside_pb2.AuthorizeConnectionReply, _abc.Awaitable[_kerbside_pb2.AuthorizeConnectionReply]]:
        """AuthorizeConnection is the core authorization call. It collapses the
        proxy's four current db.py operations into a single round trip at the
        connection decision point:
          get_token_by_token(token)   -- resolves the decrypted token plaintext,
                                         preserving the server-side expires>now
                                         filter (expired tokens are denied).
          get_source(source)          -- reads the source's ca_cert.
          get_console(source, uuid)   -- reads the hypervisor target details.
          record_channel_info_by_ref(session_id)  -- records the resolved
                                         session_id against the channel on success.
          add_audit_event('Channel created')  -- writes the creation audit event
                                         on success.
        On success it returns a Target; on any miss it returns a Denied.
        """

    @_abc_1.abstractmethod
    def RegisterChannel(
        self,
        request: _kerbside_pb2.RegisterChannelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kerbside_pb2.StatusReply, _abc.Awaitable[_kerbside_pb2.StatusReply]]:
        """RegisterChannel records the pre-authorization channel identity. It maps
        to record_channel_info_by_ref (the (node, connection_ref) upsert with the
        client/connection/channel identity fields), before the token has been
        authorized.
        """

    @_abc_1.abstractmethod
    def RecordAuditEvent(
        self,
        request: _kerbside_pb2.AuditEventRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kerbside_pb2.StatusReply, _abc.Awaitable[_kerbside_pb2.StatusReply]]:
        """RecordAuditEvent writes an audit event. It maps to add_audit_event() and
        carries the hypervisor connect success/failure and stall events the
        proxy emits during a connection's lifetime.
        """

    @_abc_1.abstractmethod
    def DeregisterChannel(
        self,
        request: _kerbside_pb2.DeregisterChannelRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kerbside_pb2.StatusReply, _abc.Awaitable[_kerbside_pb2.StatusReply]]:
        """DeregisterChannel removes a channel record at teardown. It maps to
        remove_channel_by_ref(), keyed on connection_ref alone (which is
        unique). The request carries node for symmetry with the other RPCs and
        possible future scoping, but the handler does not currently read it.
        """

    @_abc_1.abstractmethod
    def ClearNodeChannels(
        self,
        request: _kerbside_pb2.ClearNodeChannelsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kerbside_pb2.StatusReply, _abc.Awaitable[_kerbside_pb2.StatusReply]]:
        """ClearNodeChannels clears all stale channel records for a node at proxy
        startup. It maps to remove_node_channels(node).
        """

    @_abc_1.abstractmethod
    def ProxyControl(
        self,
        request: _kerbside_pb2.ProxyControlRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_kerbside_pb2.ProxyControlEvent], _abc.AsyncIterator[_kerbside_pb2.ProxyControlEvent]]:
        """ProxyControl is a server-streaming control channel from the daemon to
        the proxy. It delivers TerminateSession events (interleaved with
        Heartbeat keepalives) for sessions marked for termination that are live
        on this node. The ProxyControlEvent oneof is intentionally extensible
        (e.g. for future policy-push events); keep it extensible.
        """

def add_KerbsideProxyServicer_to_server(servicer: KerbsideProxyServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
