# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kerbside.rpc import kerbside_pb2 as kerbside__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kerbside_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KerbsideProxyStub:
    """KerbsideProxy is the control-plane RPC contract between a SPICE proxy
    process and the Kerbside daemon. Today the proxy talks to MariaDB
    directly via kerbside/db.py; this service replaces that direct database
    coupling so Python continues to own policy and the database while the
    proxy (eventually the Rust proxy, phase 3) simply consults this service.

    The service is hosted over a filesystem-guarded unix domain socket using
    insecure gRPC credentials (the peer is a trusted local process). Errors
    are signalled via gRPC status codes (context.set_code/set_details), NOT
    via fields on the reply messages. The StatusReply.success/error fields
    exist only to carry an application-level "did the bookkeeping write
    happen" result for the fire-and-forget bookkeeping RPCs; transport and
    internal failures use gRPC status codes.

    Each RPC maps to one or more of the db.py operations the proxy performs
    today (see per-RPC comments below).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthorizeConnection = channel.unary_unary(
                '/kerbside.rpc.KerbsideProxy/AuthorizeConnection',
                request_serializer=kerbside__pb2.AuthorizeConnectionRequest.SerializeToString,
                response_deserializer=kerbside__pb2.AuthorizeConnectionReply.FromString,
                _registered_method=True)
        self.RegisterChannel = channel.unary_unary(
                '/kerbside.rpc.KerbsideProxy/RegisterChannel',
                request_serializer=kerbside__pb2.RegisterChannelRequest.SerializeToString,
                response_deserializer=kerbside__pb2.StatusReply.FromString,
                _registered_method=True)
        self.RecordAuditEvent = channel.unary_unary(
                '/kerbside.rpc.KerbsideProxy/RecordAuditEvent',
                request_serializer=kerbside__pb2.AuditEventRequest.SerializeToString,
                response_deserializer=kerbside__pb2.StatusReply.FromString,
                _registered_method=True)
        self.DeregisterChannel = channel.unary_unary(
                '/kerbside.rpc.KerbsideProxy/DeregisterChannel',
                request_serializer=kerbside__pb2.DeregisterChannelRequest.SerializeToString,
                response_deserializer=kerbside__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ClearNodeChannels = channel.unary_unary(
                '/kerbside.rpc.KerbsideProxy/ClearNodeChannels',
                request_serializer=kerbside__pb2.ClearNodeChannelsRequest.SerializeToString,
                response_deserializer=kerbside__pb2.StatusReply.FromString,
                _registered_method=True)
        self.ProxyControl = channel.unary_stream(
                '/kerbside.rpc.KerbsideProxy/ProxyControl',
                request_serializer=kerbside__pb2.ProxyControlRequest.SerializeToString,
                response_deserializer=kerbside__pb2.ProxyControlEvent.FromString,
                _registered_method=True)


class KerbsideProxyServicer:
    """KerbsideProxy is the control-plane RPC contract between a SPICE proxy
    process and the Kerbside daemon. Today the proxy talks to MariaDB
    directly via kerbside/db.py; this service replaces that direct database
    coupling so Python continues to own policy and the database while the
    proxy (eventually the Rust proxy, phase 3) simply consults this service.

    The service is hosted over a filesystem-guarded unix domain socket using
    insecure gRPC credentials (the peer is a trusted local process). Errors
    are signalled via gRPC status codes (context.set_code/set_details), NOT
    via fields on the reply messages. The StatusReply.success/error fields
    exist only to carry an application-level "did the bookkeeping write
    happen" result for the fire-and-forget bookkeeping RPCs; transport and
    internal failures use gRPC status codes.

    Each RPC maps to one or more of the db.py operations the proxy performs
    today (see per-RPC comments below).
    """

    def AuthorizeConnection(self, request, context):
        """AuthorizeConnection is the core authorization call. It collapses the
        proxy's four current db.py operations into a single round trip at the
        connection decision point:
        get_token_by_token(token)   -- resolves the decrypted token plaintext,
        preserving the server-side expires>now
        filter (expired tokens are denied).
        get_source(source)          -- reads the source's ca_cert.
        get_console(source, uuid)   -- reads the hypervisor target details.
        record_channel_info(session_id)  -- records the resolved session_id
        against the channel on success.
        add_audit_event('Channel created')  -- writes the creation audit event
        on success.
        On success it returns a Target; on any miss it returns a Denied.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterChannel(self, request, context):
        """RegisterChannel records the pre-authorization channel identity. It maps
        to the proxy's first two record_channel_info() calls today (the bare
        (node, connection_ref) upsert followed by the client/connection/channel
        identity fields), before the token has been authorized.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordAuditEvent(self, request, context):
        """RecordAuditEvent writes an audit event. It maps to add_audit_event() and
        carries the hypervisor connect success/failure and stall events the
        proxy emits during a connection's lifetime.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterChannel(self, request, context):
        """DeregisterChannel removes a channel record at teardown. It maps to
        remove_proxy_channel(), keyed by (node, connection_ref).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearNodeChannels(self, request, context):
        """ClearNodeChannels clears all stale channel records for a node at proxy
        startup. It maps to remove_node_channels(node).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProxyControl(self, request, context):
        """ProxyControl is a server-streaming control channel from the daemon to
        the proxy for session-termination and policy-push events. It is defined
        now so phase 3 can pin a stable contract, but is only stubbed this phase
        (the server opens the stream and may emit keepalives). Phase 5 adds the
        real events and may extend the ProxyControlEvent oneof; keep it
        extensible.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KerbsideProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthorizeConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeConnection,
                    request_deserializer=kerbside__pb2.AuthorizeConnectionRequest.FromString,
                    response_serializer=kerbside__pb2.AuthorizeConnectionReply.SerializeToString,
            ),
            'RegisterChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterChannel,
                    request_deserializer=kerbside__pb2.RegisterChannelRequest.FromString,
                    response_serializer=kerbside__pb2.StatusReply.SerializeToString,
            ),
            'RecordAuditEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordAuditEvent,
                    request_deserializer=kerbside__pb2.AuditEventRequest.FromString,
                    response_serializer=kerbside__pb2.StatusReply.SerializeToString,
            ),
            'DeregisterChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterChannel,
                    request_deserializer=kerbside__pb2.DeregisterChannelRequest.FromString,
                    response_serializer=kerbside__pb2.StatusReply.SerializeToString,
            ),
            'ClearNodeChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearNodeChannels,
                    request_deserializer=kerbside__pb2.ClearNodeChannelsRequest.FromString,
                    response_serializer=kerbside__pb2.StatusReply.SerializeToString,
            ),
            'ProxyControl': grpc.unary_stream_rpc_method_handler(
                    servicer.ProxyControl,
                    request_deserializer=kerbside__pb2.ProxyControlRequest.FromString,
                    response_serializer=kerbside__pb2.ProxyControlEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kerbside.rpc.KerbsideProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kerbside.rpc.KerbsideProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KerbsideProxy:
    """KerbsideProxy is the control-plane RPC contract between a SPICE proxy
    process and the Kerbside daemon. Today the proxy talks to MariaDB
    directly via kerbside/db.py; this service replaces that direct database
    coupling so Python continues to own policy and the database while the
    proxy (eventually the Rust proxy, phase 3) simply consults this service.

    The service is hosted over a filesystem-guarded unix domain socket using
    insecure gRPC credentials (the peer is a trusted local process). Errors
    are signalled via gRPC status codes (context.set_code/set_details), NOT
    via fields on the reply messages. The StatusReply.success/error fields
    exist only to carry an application-level "did the bookkeeping write
    happen" result for the fire-and-forget bookkeeping RPCs; transport and
    internal failures use gRPC status codes.

    Each RPC maps to one or more of the db.py operations the proxy performs
    today (see per-RPC comments below).
    """

    @staticmethod
    def AuthorizeConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kerbside.rpc.KerbsideProxy/AuthorizeConnection',
            kerbside__pb2.AuthorizeConnectionRequest.SerializeToString,
            kerbside__pb2.AuthorizeConnectionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kerbside.rpc.KerbsideProxy/RegisterChannel',
            kerbside__pb2.RegisterChannelRequest.SerializeToString,
            kerbside__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordAuditEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kerbside.rpc.KerbsideProxy/RecordAuditEvent',
            kerbside__pb2.AuditEventRequest.SerializeToString,
            kerbside__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kerbside.rpc.KerbsideProxy/DeregisterChannel',
            kerbside__pb2.DeregisterChannelRequest.SerializeToString,
            kerbside__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearNodeChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kerbside.rpc.KerbsideProxy/ClearNodeChannels',
            kerbside__pb2.ClearNodeChannelsRequest.SerializeToString,
            kerbside__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProxyControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kerbside.rpc.KerbsideProxy/ProxyControl',
            kerbside__pb2.ProxyControlRequest.SerializeToString,
            kerbside__pb2.ProxyControlEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
