#!/bin/bash
# Launch the built kerbside-proxy Rust binary standalone, against a
# mock-grpc-server.py control-plane socket instead of a running kerbside
# daemon.
#
# Usage: start-rust-proxy.sh \
#   --tls-dir PATH \
#   --api-socket PATH \
#   --pid-file PATH \
#   --log-path PATH \
#   [--secure-port N] \
#   [--insecure-port N] \
#   [--prometheus-port N] \
#   [--vdi-address ADDR] \
#   [--node-name NAME] \
#   [--host-subject SUBJECT] \
#   [--binary PATH] \
#   [--verbose]
#
# --tls-dir must contain ca-cert.pem, proxy-cert.pem, and proxy-key.pem, as
# produced by generate-tls.sh. --api-socket is the unix domain socket the
# KerbsideProxy gRPC control service listens on -- point it at the same
# socket path passed to mock-grpc-server.py's --socket.
#
# The binary is NOT built by this script. The rust/kerbside-proxy crate
# builds in Docker with the repo mounted (see rust/kerbside-proxy/Makefile
# and Dockerfile), so this script only locates an already-built binary:
#   - a release build, produced by running (from the repo root)
#       cd rust/kerbside-proxy && \
#       docker run --rm -v "$(pwd)/../..":/repo \
#         -v "$(pwd)/.cargo-cache/registry":/usr/local/cargo/registry \
#         -v "$(pwd)/.cargo-cache/git":/usr/local/cargo/git \
#         -w /repo/rust/kerbside-proxy -u "$(id -u)":"$(id -g)" -e HOME=/tmp \
#         kerbside-proxy-dev cargo build --release
#     (mirrors the Makefile's DOCKER_RUN invocation, with --release added;
#     `make image` must have been run at least once to build
#     kerbside-proxy-dev), landing at
#     rust/kerbside-proxy/target/release/kerbside-proxy; or
#   - a debug build via the existing Makefile target:
#       make -C rust/kerbside-proxy build
#     landing at rust/kerbside-proxy/target/debug/kerbside-proxy.
# A release binary is preferred when both exist. Pass --binary to point at
# a specific binary instead of auto-detecting.
#
# Backgrounds the proxy (not double-forked; matches start-kerbside.sh's
# pattern) and writes its PID to --pid-file. Polls the secure, insecure,
# and Prometheus ports until they accept TCP connections (or times out and
# dumps the log) before returning, so callers do not need their own
# readiness loop.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

TLS_DIR=''
API_SOCKET=''
PID_FILE=''
LOG_PATH=''
SECURE_PORT='5900'
INSECURE_PORT='5901'
PROMETHEUS_PORT='13030'
VDI_ADDRESS='0.0.0.0'
NODE_NAME='kerbside-proxy-verify'
# Must match the subject of proxy-cert.pem as generated by generate-tls.sh
# (subj '/C=US/O=Kerbside CI/CN=kerbside-ci').
HOST_SUBJECT='C=US,O=Kerbside CI,CN=kerbside-ci'
BINARY=''
VERBOSE='0'

while [ $# -gt 0 ]; do
    case "$1" in
        --tls-dir)          TLS_DIR="$2";         shift 2 ;;
        --api-socket)       API_SOCKET="$2";      shift 2 ;;
        --pid-file)         PID_FILE="$2";        shift 2 ;;
        --log-path)         LOG_PATH="$2";        shift 2 ;;
        --secure-port)      SECURE_PORT="$2";     shift 2 ;;
        --insecure-port)    INSECURE_PORT="$2";   shift 2 ;;
        --prometheus-port)  PROMETHEUS_PORT="$2"; shift 2 ;;
        --vdi-address)      VDI_ADDRESS="$2";     shift 2 ;;
        --node-name)        NODE_NAME="$2";       shift 2 ;;
        --host-subject)     HOST_SUBJECT="$2";    shift 2 ;;
        --binary)           BINARY="$2";          shift 2 ;;
        --verbose)          VERBOSE='1';          shift 1 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

for arg in TLS_DIR API_SOCKET PID_FILE LOG_PATH; do
    if [ -z "${!arg}" ]; then
        echo "ERROR: --${arg,,} is required (use dashes, not underscores)" >&2
        exit 1
    fi
done

# ── Locate TLS material ───────────────────────────────────────────────────────

CERT="${TLS_DIR}/proxy-cert.pem"
CERT_KEY="${TLS_DIR}/proxy-key.pem"
CACERT="${TLS_DIR}/ca-cert.pem"

for f in "${CERT}" "${CERT_KEY}" "${CACERT}"; do
    if [ ! -f "${f}" ]; then
        echo "ERROR: TLS material not found: ${f} (run generate-tls.sh first)" >&2
        exit 1
    fi
done

# ── Locate the built binary ───────────────────────────────────────────────────

if [ -z "${BINARY}" ]; then
    RELEASE_BINARY="${REPO_ROOT}/rust/kerbside-proxy/target/release/kerbside-proxy"
    DEBUG_BINARY="${REPO_ROOT}/rust/kerbside-proxy/target/debug/kerbside-proxy"
    if [ -x "${RELEASE_BINARY}" ]; then
        BINARY="${RELEASE_BINARY}"
    elif [ -x "${DEBUG_BINARY}" ]; then
        BINARY="${DEBUG_BINARY}"
        echo "[start-rust-proxy] WARNING: using debug build ${DEBUG_BINARY}; a release build is preferred" >&2
    else
        echo "ERROR: no kerbside-proxy binary found at:" >&2
        echo "  ${RELEASE_BINARY}" >&2
        echo "  ${DEBUG_BINARY}" >&2
        echo "Build one first -- see the comment block at the top of this script for the" >&2
        echo "exact Docker invocation (debug: 'make -C rust/kerbside-proxy build')." >&2
        exit 1
    fi
fi

if [ ! -x "${BINARY}" ]; then
    echo "ERROR: kerbside-proxy binary is not executable: ${BINARY}" >&2
    exit 1
fi

echo "[start-rust-proxy] Using binary: ${BINARY}"

# ── Launch ─────────────────────────────────────────────────────────────────────

ARGS=(
    --vdi-address "${VDI_ADDRESS}"
    --secure-port "${SECURE_PORT}"
    --insecure-port "${INSECURE_PORT}"
    --cert "${CERT}"
    --cert-key "${CERT_KEY}"
    --cacert "${CACERT}"
    --host-subject "${HOST_SUBJECT}"
    --node-name "${NODE_NAME}"
    --prometheus-port "${PROMETHEUS_PORT}"
    --api-socket "${API_SOCKET}"
)
if [ "${VERBOSE}" = '1' ]; then
    ARGS+=(--verbose)
fi

echo "[start-rust-proxy] Launching: ${BINARY} ${ARGS[*]}"

"${BINARY}" "${ARGS[@]}" >> "${LOG_PATH}" 2>&1 &
PROXY_PID=$!
printf '%d' "${PROXY_PID}" > "${PID_FILE}"
echo "[start-rust-proxy] kerbside-proxy started, pid=${PROXY_PID}"

# ── Wait for the listeners to come up ─────────────────────────────────────────
#
# main.rs binds the insecure/secure SPICE listeners and the Prometheus
# metrics listener concurrently via tokio::select!; there is no single
# readiness signal, so poll all three with plain TCP connect attempts. If
# the process has already exited (e.g. a bad cert path), fail fast instead
# of waiting out the full deadline.

_wait_for_port() {
    local label="$1"
    local port="$2"
    local deadline
    deadline=$(( $(date +%s) + 15 ))
    while true; do
        if ! kill -0 "${PROXY_PID}" 2>/dev/null; then
            echo "ERROR: kerbside-proxy (pid ${PROXY_PID}) exited before ${label} came up" >&2
            echo "  log (last 60 lines):" >&2
            tail -60 "${LOG_PATH}" >&2 || true
            exit 1
        fi
        if python3 -c \
                "import socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1', ${port})); s.close()" \
                2>/dev/null; then
            break
        fi
        if [ "$(date +%s)" -ge "${deadline}" ]; then
            echo "ERROR: kerbside-proxy ${label} did not come up on port ${port} within 15s" >&2
            echo "  log (last 60 lines):" >&2
            tail -60 "${LOG_PATH}" >&2 || true
            exit 1
        fi
        sleep 0.5
    done
    echo "[start-rust-proxy] ${label} up on port ${port}"
}

_wait_for_port 'insecure SPICE listener' "${INSECURE_PORT}"
_wait_for_port 'secure SPICE listener' "${SECURE_PORT}"
_wait_for_port 'Prometheus metrics listener' "${PROMETHEUS_PORT}"

echo "[start-rust-proxy] kerbside-proxy up, pid=${PROXY_PID}"
