name: Test cloud compatibility

on:
  workflow_dispatch:
    inputs:
      retention:
        description: 'How long to retain the environment after the workflow run in minutes'
        required: true
        default: '0'
  pull_request:
    branches:
      - develop

jobs:
  functional_matrix:
    name: "${{ matrix.test.description }}"
    strategy:
      fail-fast: false
      matrix:
        test: [
          {
            'name': 'ovirt-44-rocky-8',
            'description': 'oVirt 4.4 on Rocky 8',
            'ovirt_rpm': 'https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm',
            'ovirt_repos_patch': 'ovirt-4.4-rocky-8-repos.patch',
            'base': 'rocky:8',
            'baseuser': 'cloud-user'
          },
          {
            'name': 'ovirt-45-rocky-8',
            'description': 'oVirt 4.5 on Rocky 8',
            'ovirt_rpm': 'centos-release-ovirt45',
            'ovirt_repos_patch': 'ovirt-4.5-rocky-8-repos.patch',
            'base': 'rocky:8',
            'baseuser': 'cloud-user'
          },
          {
            'name': 'ovirt-45-rocky-9',
            'description': 'oVirt 4.5 on Rocky 9',
            'ovirt_rpm': 'centos-release-ovirt45',
            'ovirt_repos_patch': 'ovirt-4.5-rocky-9-repos.patch',
            'base': 'rocky:9',
            'baseuser': 'cloud-user'
          },
        ]
    runs-on: [self-hosted, vm]
    timeout-minutes: 120
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.test.name }}
      cancel-in-progress: true

    # NOTE(mikal): git repos are checked out to /srv/github/_work/{org}/{repo}
    # which is available as GITHUB_WORKSPACE. You can find other environment
    # variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

    steps:
      - name: Set environment variables
        shell: bash
        run: |
          echo "SF_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout the actions repository
        uses: actions/checkout@v4
        with:
          repository: shakenfist/actions
          path: actions
          fetch-depth: 0

      - name: Checkout kerbside
        uses: actions/checkout@v4
        with:
          path: kerbside
          fetch-depth: 0

      - name: Build infrastructure
        shell: bash
        run: |
          . $GITHUB_ENV
          ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} base=${{ matrix.test.base }}" \
              --tags all ${GITHUB_WORKSPACE}/actions/ansible/kerbside-single-node.yml

      - name: Install base packages
        run: |
          . $GITHUB_ENV

          script="export PS4='=======================\n+ '; set -x;"
          script="${script} sudo dnf update -y;"
          script="${script} sudo dnf install -y epel-release;"
          script="${script} sudo crb enable;"
          script="${script} sudo dnf update -y;"
          script="${script} sudo dnf install -y vim patch;"
          script="${script} sudo chown ${{ matrix.test.baseuser }}:${{ matrix.test.baseuser }} /srv;"

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              "${script}"

      - name: Install upstream oVirt release package
        run: |
          . $GITHUB_ENV

          script="export PS4='=======================\n+ '; set -x;"
          script="${script} sudo dnf install -y ${{ matrix.test.ovirt_rpm }};"

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              "${script}"

      - name: Copy oVirt yum repos patch to target node
        run: |
          . $GITHUB_ENV

          scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            ${GITHUB_WORKSPACE}/kerbside/etc/${{ matrix.test.ovirt_repos_patch }} \
            ${{ matrix.test.baseuser }}@10.0.2.2:/srv/

      - name: Apply repos patch
        run: |
          . $GITHUB_ENV

          script="export PS4='=======================\n+ '; set -x;"
          script="${script} cd /etc/yum.repos.d;"
          script="${script} sudo patch -p1 < /srv/${{ matrix.test.ovirt_repos_patch }};"

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              "${script}"

      - name: Further package configuration
        run: |
          . $GITHUB_ENV

          script="export PS4='=======================\n+ '; set -x;"
          script="${script} sudo dnf update -y;"
          script="${script} sudo dnf module -y enable javapackages-tools;"
          script="${script} sudo dnf module -y enable postgresql:12;"
          script="${script} sudo dnf module -y enable mod_auth_openidc:2.3;"
          script="${script} sudo dnf module -y enable nodejs:14;"
          script="${script} sudo dnf module -y enable pki-deps;"
          script="${script} sudo dnf distro-sync --nobest -y;"

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              "${script}"

      - name: Gather artifacts
        if: always()
        run: |
          . $GITHUB_ENV

          script="export PS4='=======================\n+ '; set -x;"
          script="${script} sudo zip -r /tmp/bundle.zip "
              script="${script} /etc/yum.repos.d "
              script="${script} /var/lib/ovirt-engine/setup "
              script="${script} || true;"
          script="${script} sudo chmod ugo+r /tmp/bundle.zip;"
          script="${script} ls -lrth /tmp/bundle.zip;"

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              "${script}"

          mkdir -p /srv/github/artifacts/bundle/
          scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2:/tmp/bundle.zip \
              /srv/github/artifacts/bundle/

          cd /srv/github/artifacts/bundle/
          unzip bundle.zip
          rm bundle.zip
          cd ..
          zip bundle.zip bundle

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-${{ matrix.test.name }}
          retention-days: 90
          if-no-files-found: error
          path: /srv/github/artifacts/bundle.zip

      - name: Retain the environment if requested
        if: github.event_name == 'workflow_dispatch'
        run: sleep $(( $MINUTES * 60 ))
        env:
          MINUTES: ${{ inputs.retention }}